steps:
  - label: ":shell: Tests"
    plugins:
      docker-compose#v4.9.0:
        run: tests

  - label: ":sparkles: Lint"
    plugins:
      plugin-linter#v3.0.0:
        id: aws-ssm

  - label: ":shell: Shellcheck"
    plugins:
      shellcheck#v1.3.0:
        files: hooks/**
